apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-minion
  namespace: default
  labels: 
    app: kafka-minion
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: kafka-minion
  template:
    metadata:
      labels: 
        app: kafka-minion
    spec:
      containers:
      - name: kafka-minion
        image: solsson/kafka-consumers-prometheus@sha256:b5f5b8672397f94379a5a3e8b4bf41cf12b64ff1c4fc7f84684edca4beb37c16
        env:
        - name: TELEMETRY_HOST
          value: prometheus-service.router.monitoring.svc.cluster.local
        - name: TELEMETRY_PORT
          value: "8080"
        - name: EXPORTER_IGNORE_SYSTEM_TOPICS
          value: "true"
        - name: EXPORTER_METRICS_PREFIX
          value: kafka_minion
        - name: LOG_LEVEL
          value: info
        - name: KAFKA_BROKERS
          value: kafka-headless:9092
        - name: KAFKA_CONSUMER_OFFSETS_TOPIC_NAME
          value: __consumer_offsets
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            port: http
            path: /readycheck
        livenessProbe:
          httpGet:
            port: http
            path: /healthcheck
