kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: mongo-pvc
spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: ibmc-file-bronze
   resources:
     requests:
       storage: 1Gi
