apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  kafka-broker: kafka
  kafka-broker-port: "9092"
  kafka-topic-name: test
# consumer definition
  consumer-group-id-1: test-group
  consumer-group-id-2: sample-group
  key-string-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-string-serializer: org.apache.kafka.common.serialization.StringSerializer
  message-per-request: "10"
